before_install:
  - gem install bundler
  - git submodule update --init --recursive

rvm:
  - 2.2.2 # NOTE: 2.2.1 or lower aren't supported by activesupport 5.0, CI isn't needed for such legacy versions.
  - 2.2.5
  - 2.3.1

jdk:
  - oraclejdk8